# todomvc-app-config

#logging.level.: ${LOGGING_LEVEL_:INFO}
logging:
  file: ${LOGGING_FILE:oss-todomvc-app}.log
  level.: ${LOGGING_LEVEL_:INFO}
  level:
    org.springframework.amqp: ${LOGGING_LEVEL_:INFO}
    com.netflix.discovery.TimedSupervisorTask: OFF # TODO switch this off
  path: ${LOGGING_PATH:${user.home}/data/oss-todomvc-app/logs}

app:
  error:
    handlerEnabled: false # 统一异常处理禁用@ControllerAdvice方式
  type: RESOURCE
  security:
    basePath: '/api'
    defaultTestUser: test_user
    enabled: true
    permited: '/api/greeting,/hal/**'

app-default-only: app-default-only

security:
  #ignored: '/css/**,/js/**,/images/**,/webjars/**,/**/favicon.ico'
  ignored: '/health, /src'
  user:
    name: ${SECURITY_USER_NAME:todomvc-admin}
    password: ${SECURITY_USER_PASSWORD:todomvc-admin_pass}
    role: ADMIN

server:
  port: ${SERVER_PORT:8080}
  error:
    includeStacktrace: ALWAYS

spring.datasource:
  continue-on-error: false # Do not stop if an error occurs while initializing the database.
  #data:  # Data (DML) script resource reference.
  initialize: false # Populate the database using 'data.sql'.
  jmx-enabled: false # Enable JMX support (if provided by the underlying pool).
  #jndi-name:  # JNDI location of the datasource. Class, url, username & password are ignored when set.
  maximum-pool-size: 10
  minimum-idle: 5
  name: dataSource
  test-while-idle: true
  time-between-eviction-runs-millis: 1
  validation-query: 'SELECT 1'
  type: 'com.zaxxer.hikari.HikariDataSource'
  driver-class-name: 'org.h2.Driver'
  url: 'jdbc:h2:mem:oss-todomvc-app'
  username: sa
  #password:

# H2 Web Console (H2ConsoleProperties)
spring.h2.console:
  enabled: true # Enable the console.
  path: '/h2-console' # Path at which the console will be available.

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
spring.data.jpa.repositories.enabled: true # Enable JPA repositories.
spring.data.rest:
  base-path: '/hal/api'
spring.jpa:
  database: H2 # Target database to operate on, auto-detected by default. Can be alternatively set using the "databasePlatform" property.
  database-platform: 'org.hibernate.dialect.H2Dialect' # Name of the target database to operate on, auto-detected by default. Can be alternatively set using the "Database" enum.
  generate-ddl: true # Initialize the schema on startup.
  hibernate.ddl-auto: create-drop # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
  hibernate.naming-strategy: 'org.hibernate.cfg.ImprovedNamingStrategy' # Naming strategy fully qualified name.
  show-sql: true # Enable logging of SQL statements.

greeting: '{cipher}AQAIqgFSJgWPiqgFGOtsxqrpHV3nFSMYwJqTTKTp0hfJq1/DEOJJwE0vizjK582MU11f8iUJKfnJN4LM4rItOH9Q5FLh1cx/TIDRJF6N8DOePwEA8rqgvnSDMeDJXrV9N5U3DPGovwQTUVMnmfEZVq8z9CdPu1Z+DNs/zWbFcA8D9kAHNMrzSdDFmyOa7+9ZnKXPTrcZvaM5fNliDUxv/ER2tlQAPq2MY4xpFrs74lr+qgydz1vtRfUegjd6r4o3GaqE96vxXIkDks/A3nrsBxZnZx27uEw3WHi8f9ft1vZWFLGlH9R86BdaalEIu5buIVSsdfmdtaKEbO2rBw/uV9dJtcMppQolbGowTI/KdGJdojspapteJtfkmfk9KnaqhaQ='

---
spring:
  profiles: oauth2

security:
  oauth2.resource.userInfoUri: http://local-auth2:9999/uaa/user

---
spring:
  profiles: default

---
spring:
  profiles: development.env

app-env_development-only: development.env

---
spring:
  profiles: it.env

---
spring:
  profiles: staging.env

---
spring:
  profiles: production.env

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://local-mysql:3306/oss-todomvc-app?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: root

spring.h2.console.enabled: false

spring.jpa:
  database: MYSQL
  database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
  generate-ddl: false
  hibernate.ddl-auto: none
  show-sql: false
